import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, Bot, Image, Eye, Moon, Sun, Gauge, CreditCard, Sparkles, ShieldCheck } from 'lucide-react'
import { useTheme } from '../context/ThemeContext'
export function Landing() {
  const { theme, toggleTheme } = useTheme()
  return (
    <main className="min-h-screen overflow-hidden"><section className="mx-auto max-w-7xl px-4 py-8 md:py-10">
      <nav className="mb-16 flex items-center justify-between rounded-3xl border border-white/10 bg-white/50 px-4 py-3 backdrop-blur-xl dark:bg-white/5"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-electric to-cyanx text-white shadow-glow"><Sparkles size={20} /></div><h1 className="text-2xl font-black">NexAI</h1></div><div className="flex items-center gap-3"><button onClick={toggleTheme} className="rounded-2xl border border-black/10 bg-white/60 p-3 shadow-sm transition hover:bg-white/80 dark:border-white/10 dark:bg-white/5 dark:hover:bg-white/10" aria-label="Toggle theme">{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><Link to="/login" className="btn-secondary">Login</Link></div></nav>
      <div className="grid items-center gap-10 xl:grid-cols-[1fr_520px]"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55 }}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm font-semibold text-cyanx"><ShieldCheck size={16} />Premium React AI SaaS Template</div><h2 className="max-w-5xl text-5xl font-black leading-tight md:text-7xl">Build an AI SaaS dashboard that looks ready for launch.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-black/55 dark:text-white/55">NexAI includes AI chat, image generation, vision analysis, billing, users, invoices, API keys, usage limits, integrations, and premium responsive dashboard screens.</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/dashboard" className="btn-primary flex items-center gap-2">View Dashboard <ArrowRight size={18} /></Link><Link to="/register" className="btn-secondary">Get Started</Link></div><div className="mt-10 grid max-w-2xl grid-cols-3 gap-3">{[['15+', 'Pages'], ['100%', 'Responsive'], ['2', 'Themes']].map(([value, label]) => <div key={label} className="rounded-3xl border border-white/10 bg-white/10 p-4 backdrop-blur-xl"><p className="text-2xl font-black">{value}</p><p className="text-sm text-white/45">{label}</p></div>)}</div></motion.div>
      <motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.6, delay: 0.1 }} className="card"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold text-cyanx">Live Preview</p><h3 className="text-2xl font-bold">AI Command Center</h3></div><span className="badge bg-emerald-400/10 text-emerald-300">Online</span></div><div className="grid gap-3 sm:grid-cols-2">{[['Requests','128.4K'],['Users','12.8K'],['Revenue','$42.1K'],['Latency','320ms']].map(([label,value]) => <div key={label} className="rounded-3xl border border-white/10 bg-white/5 p-4"><p className="text-sm text-white/45">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div><div className="mt-4 rounded-3xl border border-white/10 bg-white/5 p-4"><div className="mb-3 flex items-center justify-between text-sm"><span className="font-semibold">AI Usage</span><span className="text-cyanx">+18.2%</span></div><div className="flex h-32 items-end gap-2">{[42,58,49,74,62,88,76,92,68,84].map((h,i) => <div key={i} className="w-full rounded-t-xl bg-gradient-to-t from-electric to-cyanx" style={{height:`${h}%`}} />)}</div></div></motion.div></div>
      <div className="mt-20 grid gap-5 md:grid-cols-3 xl:grid-cols-5">{[['AI Chat',Bot],['Image Generator',Image],['Vision Analysis',Eye],['Usage Limits',Gauge],['Billing UI',CreditCard]].map(([label, Icon]: any) => <div key={label} className="card transition hover:-translate-y-1"><Icon className="text-cyanx" /><h3 className="mt-5 text-xl font-bold">{label}</h3><p className="mt-2 text-sm leading-6 text-black/50 dark:text-white/50">Production-ready UI block designed for modern AI SaaS products.</p></div>)}</div>
    </section></main>
  )
}
